### ISSUE TITLE
remove STHVN

### ISSUE THREAD

**Issue by isanti** [emo-bon/governance-data#20]
STHVN (MSS) observatory never collected any material samples, data, sampling metadata etc. It is no longer part of EMO BON. Needs to be removed.

1) remove STHVN from the governance-data/logsheets.csv @isanti 
2) remove the observatory-sthvn-crate repository @bulricht

**Comment by isanti** [comment]
Ok, I removed it from the governance-data/logsheets.csv

**Comment by bulricht** [comment]
repo is gone as well
