### ISSUE TITLE
dealing with ranges and limits in the ENA XML and RDF parts of the data workflow

### ISSUE THREAD

**Issue by kmexter** [emo-bon/governance-data#30]
We agreed that
- where depth is given as a range, that will be stored as a range in the RDF files but needs to be stored as a single value in the ENA samples submission XML files so the depth max will be taken
- where measurements are given as a limit  (upper limit - if lower limit one should flag that as a QC issue) then that should be stored as a max value with no min value (or min value = 0). If this happens for a mandatory measurement in the ENA checklist, then we will then enter "NA" (or "not measured" or nothing if the value has to be a float) 

I am slightly worried about the fact that we will have, in our RDF files, a mix of properties - some events will have 
depth = 10
chla = 1.2

and others will have
min depth = 10
max depth = 20
max chla = 2
min chla = 0.2

For a human reading this, it is not a problem, but humans are not the focus of these RDF files. machines are. And if they ask for the "depth" they will not get the data that has "min depth": the query has to know to ask for "min depth and max depth". 
Again, not an issue, but not very tidy on our side -> we know what is in our RDF files, but others do not so they will be less able to navigate our eventual triple store

I was wondering therefore  if we should record, in our ttl files, *everything* as a max and min (well, give every measurement a max and min property)?

**Comment by laurianvm** [comment]
will be taken up in https://github.com/emo-bon/observatory-profile/issues/21
