### ISSUE TITLE
material sample ids in measured sheets were not changed

### ISSUE THREAD

**Issue by kmexter** [emo-bon/governance-data#31]
When you copy a sheet to a new one in a googlesheet and then rename it, then any equation "follows" that renaming, This means for example that in BPNS sediment (https://docs.google.com/spreadsheets/d/1zc0bZdpl-Eoi35lI_5BGkElbscplyQRyNPLkSgeEyEQ/edit?gid=15718907#gid=15718907), the equation in the measured tab for the first column says 
='old sampling'!AL4 
instead of 
='sampling'!AL4 

Can you please check and change this for all the logsheets (wa and so and maybe arms?) asap as this is stopping the correct harvest into github. thanks!

**Comment by melinalou** [comment]
ckecked and corrected

**Comment by kmexter** [comment]
thanks!
